requires 'CallBackery', '>= 0.38.0';
requires 'Mojo::SQLite';
requires 'Wireguard::WGmeta', '>= 0.3.0';
requires 'Net::IP', '>=1.26';
requires 'Email::MIME';
requires 'Email::Sender';
requires 'Text::QRCode';
requires 'YAML::XS';
requires 'SVG::Barcode';
requires 'SVG::Barcode::QRCode';
requires 'YAML::PP';