requires 'CallBackery', '>= 0.36.9';
requires 'Mojo::SQLite';
requires 'Wireguard::WGmeta', '>= 0.2.3';
requires 'Net::IP', '>=1.26';
requires 'Email::MIME';
requires 'Email::Sender';
requires 'Text::QRCode';
requires 'YAML::XS';
requires 'SVG::Barcode';
requires 'SVG::Barcode::QRCode';
requires 'YAML::PP';