#!/bin/sh

PKGNAME=wg-wrangler
USERNAME=wg-wrangler_manager
GROUPNAME=wg-wrangler_manager

# Create user and group
adduser --system --group --no-create-home $USERNAME

# set permissions and group membership on /etc/wireguard
chgrp --silent --recursive $GROUPNAME /etc/wireguard/
# set group permissions
chmod g+rwx /etc/wireguard
chmod -R g+rw /etc/wireguard

# set permissions for /opt/wg-wrangler/etc dir
chgrp --silent --recursive $GROUPNAME /etc/opt/$PKGNAME/
# set group permissions
chmod -R g+rwx /etc/opt/$PKGNAME/

# create var directory
mkdir -p /var/opt/$PKGNAME
chown --silent --recursive $USERNAME /var/opt/$PKGNAME

# Whitelist wg* commands for us
echo "%$GROUPNAME ALL=NOPASSWD: /usr/bin/wg*" >> /etc/sudoers.d/$PKGNAME

