name: Unit Tests

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
        node:
          - '18.x'
          - '16.x'
        exclude:
          - os: ubuntu-22.04
            node: '16.x'
          - os: ubuntu-20.04
            node: '16.x'
          - os: ubuntu-18.04
            node: '18.x'
      fail-fast: false
    name: node-${{ matrix.node }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: CPAN Cache
      id: cpan-cache
      uses: actions/cache@v1
      with:
        path: thirdparty
        key: ${{ matrix.os }}-cpan-${{ matrix.perl }}-${{ hashFiles('**/cpanfile') }}
    - name: Node Cache
      id: node-cache
      uses: actions/cache@v1
      with:
        path: frontend/node_modules
        key: ${{ matrix.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.os }}-node-${{ matrix.node }}-
    - name: Install OS dependencies
      run: sudo apt install libqrencode-dev pkg-config gettext
    - name: Bootstrap
      run: ./bootstrap
    - name: Configure
      run: ./configure --prefix=$HOME/test-install
    - name: Make
      run: make
    - name: Test
      run: |
          cp etc/wgwrangler.dist.yaml  etc/wgwrangler.yaml
          make test
    - name: Check Dist
      run: |
        make dist
        tar xf *-$(cat VERSION).tar.gz
        cd *-$(cat VERSION)
        ./configure --prefix=$HOME/test-install
        make
        make install
        cd $HOME/test-install
        cp etc/wgwrangler.dist.yaml  etc/wgwrangler.yaml
        ./bin/wgwrangler
    - name: Cache Prep
      run: |
        rm thirdparty/Makefile* thirdparty/cpan*snapshot
